version: '3.8'

services:
  frontend:
    image: microboard/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - frontend-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_api_gateway_config
        target: /etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - post-service
      - comment-service
    networks:
      - frontend-net
      - backend-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M

  auth-service:
    image: microboard/auth-service:latest
    environment:
      - DB_HOST=auth-db
      - DB_NAME=authdb
      - DB_USER=authuser
      - DB_PASSWORD=authpass
      - NODE_ENV=production
      - PORT=3001
    secrets:
      - source: jwt_secret
        target: jwt_secret
    networks:
      - backend-net
      - db-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  post-service:
    image: microboard/post-service:latest
    environment:
      - DB_HOST=post-db
      - DB_NAME=postdb
      - DB_USER=postuser
      - DB_PASSWORD=postpass
      - AUTH_SERVICE_URL=http://auth-service:3001
      - NODE_ENV=production
      - PORT=3002
    networks:
      - backend-net
      - db-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  comment-service:
    image: microboard/comment-service:latest
    environment:
      - DB_HOST=comment-db
      - DB_NAME=commentdb
      - DB_USER=commentuser
      - DB_PASSWORD=commentpass
      - AUTH_SERVICE_URL=http://auth-service:3001
      - POST_SERVICE_URL=http://post-service:3002
      - NODE_ENV=production
      - PORT=3003
    networks:
      - backend-net
      - db-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  auth-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - db-net
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  post-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: postdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - post-db-data:/var/lib/postgresql/data
    networks:
      - db-net
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  comment-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: commentuser
      POSTGRES_PASSWORD: commentpass
      POSTGRES_DB: commentdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - comment-db-data:/var/lib/postgresql/data
    networks:
      - db-net
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  frontend-net:
    external: true
  backend-net:
    external: true
  db-net:
    external: true

volumes:
  auth-db-data:
  post-db-data:
  comment-db-data:

secrets:
  jwt_secret:
    external: true

configs:
  nginx_api_gateway_config:
    external: true